services:
  app:
    build: .
    container_name: gute-schule-jetzt-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev

networks:
  default:
    name: gute-schule-jetzt-dev-network